# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-27 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20170927_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_price',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_quantity',
            field=models.IntegerField(max_length=100),
        ),
    ]
