# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-29 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_auto_20170928_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=5),
        ),
    ]
