# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-29 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0002_auto_20170929_1525'),
        ('Product', '0008_auto_20170929_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dealer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Dealer.Dealer'),
        ),
    ]
