# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-30 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_product_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
