# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-30 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_auto_20170930_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='product_price',
            field=models.FloatField(),
        ),
    ]
