# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-02 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_auto_20170930_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('number', models.IntegerField(blank=True)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='dealer',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.Supplier'),
        ),
    ]
