# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-02 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_auto_20171002_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
