# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-02 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_auto_20171002_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.Supplier'),
        ),
    ]
