# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-02 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0002_auto_20170929_1525'),
        ('Product', '0017_inventory_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='supplier',
        ),
        migrations.AddField(
            model_name='inventory',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dealer.Dealer'),
        ),
    ]
