# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-29 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='dealer_address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='dealer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='dealer_name',
            field=models.CharField(help_text='Dealer Name', max_length=100),
        ),
    ]
