# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-04 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dealer', '0003_auto_20171004_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('date_paid', models.DateField()),
                ('amount', models.FloatField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dealer.Dealer')),
            ],
        ),
    ]
